const char page1[] PROGMEM = // todo: use gzip
   "<!DOCTYPE html>\n"
   "<html lang=\"en\">\n"
   "<head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n"
   "<title>WiFi Garage Door Opener</title>\n"
   "<style type=\"text/css\">\n"
   "div,table,input{\n"
   "border-radius: 5px;\n"
   "margin-bottom: 5px;\n"
   "box-shadow: 2px 2px 12px #000000;\n"
   "background-image: -moz-linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-image: -ms-linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-image: -o-linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-image: -webkit-linear-gradient(top, #efffff, #50a0ff);\n"
   "background-image: linear-gradient(top, #ffffff, #50a0ff);\n"
   "background-clip: padding-box;\n"
   "}\n"
   "body{width:230px;font-family: Arial, Helvetica, sans-serif;}\n"
   ".style5 {\n"
   "border-radius: 5px;\n"
   "box-shadow: 0px 0px 15px #000000;\n"
   "background-image: -moz-linear-gradient(top, #ff00ff, #ffa0ff);\n"
   "background-image: -ms-linear-gradient(top, #ff00ff, #ffa0ff);\n"
   "background-image: -o-linear-gradient(top, #ff00ff, #ffa0ff);\n"
   "background-image: -webkit-linear-gradient(top, #ff0000, #ffa0a0);\n"
   "background-image: linear-gradient(top, #ff00ff, #ffa0ff);\n"
   "}\n"
   "</style>\n"
   "<script type=\"text/javascript\">\n"
   "a=document.all\n"
   "oledon=0\n"
   "function startEvents(){\n"
   "var loc = window.location\n"
   "ws = new WebSocket(\"ws://\"+loc.host+\"/ws\")\n"
   "ws.onopen = function(evt) { }\n"
   "ws.onclose = function(evt) { alert(\"Connection closed.\"); }\n"
   "ws.onmessage = function(evt) {\n"
   " lines = evt.data.split(';')\n"
   " event=lines[0]\n"
   " data=lines[1]\n"
   " if(event == 'state')\n"
   " {\n"
   " d=JSON.parse(data)\n"
   " dt=new Date(d.t*1000)\n"
   " a.time.innerHTML=dt.toLocaleTimeString()\n"
   " a.car.innerHTML=d.car?\"IN\":\"OUT\"\n"
   " a.car.setAttribute('class',d.car?'':'style5')\n"
   " a.door.innerHTML=d.door?\"OPEN\":\"CLOSED\"\n"
   " a.door.setAttribute('class',d.door?'style5':'')\n"
   " a.doorBtn.value=d.door?\"Close\":\"Open\"\n"
   " a.temp.innerHTML=d.temp+\"&degF\"\n"
   " a.rh.innerHTML=d.rh+\"%\"\n"
   " a.ct.innerHTML=d.ct\n"
   " a.tz.innerHTML=d.tz\n"
   " oledon=d.o\n"
   " a.OLED.value=oledon?'ON ':'OFF'\n"
   " }\n"
   " else if(event == 'alert')\n"
   " {\n"
   "  alert(data)\n"
   " }\n"
   "}\n"
   "}\n"
   "function setVar(varName, value)\n"
   "{\n"
   " ws.send('cmd;{\"key\":\"'+a.myKey.value+'\",\"'+varName+'\":'+value+'}')\n"
   "}\n"
   "function setDDelay()\n"
   "{\n"
   " setVar('doorDelay', a.dc.value)\n"
   "}\n"
   "function setCTimeout()\n"
   "{\n"
   " setVar('closetimeout', a.ct.value)\n"
   "}\n"
   "function setTZ()\n"
   "{\n"
   " setVar('TZ', a.tz.value)\n"
   "}\n"
   "function oled(){\n"
   "oledon=!oledon\n"
   "setVar('oled', oledon)\n"
   "a.OLED.value=oledon?'ON ':'OFF'\n"
   "}\n"
   "</script>\n"
   "<body onload=\"{\n"
   "key=localStorage.getItem('key')\n"
   "if(key!=null) document.getElementById('myKey').value=key\n"
   "startEvents()\n"
   "}\">\n"
   "<div><h3>WiFi Garage Door Opener </h3>\n"
   "<table align=center>\n"
   "<tr align=center><td><p id=\"time\"> 0:00:00 AM</p></td><td><input type=\"button\" value=\"Open\" id=\"doorBtn\" onClick=\"{setVar('door',0)}\"></td></tr>\n"
   "<tr><td><input id='dc' type=text size=4 value='10'><input value=\"Set\" type='button' onClick=\"{setDDelay()}\"></td>\n"
   "<td align=center><input type=\"button\" value=\"Delayed\" id=\"doorBtn\" onClick=\"{setVar('door',1)}\"></td></tr>\n"
   "<tr align=center><td>Garage</td><td>Car</td></tr>\n"
   "<tr align=center><td><div id=\"door\">CLOSED</div></td><td><div id=\"car\">IN</div></td></tr>\n"
   "<tr align=\"center\"><td><div id=\"temp\">00.0&degF</div></td><td><div id=\"rh\">00.0%</div></td></tr>\n"
   "<tr align=center><td>Timeout</td><td>Timezone</td></tr>\n"
   "<tr><td><input name='ct' id='ct' type=text size=4 value='60'><input value=\"Set\" type='button' onclick=\"{setCTimeout()}\"></td>\n"
   "<td><input name='tz' id='tz' type=text size=4 value='-5'><input value=\"Set\" type='button' onclick=\"{setTZ()}\"></form></td></tr>\n"
   "<tr><td>Display:</td><td><input type=\"button\" value=\"OFF\" id=\"OLED\" onClick=\"{oled()}\"></td></tr>\n"
   "</table>\n"
   "<input id=\"myKey\" name=\"key\" type=text size=50 placeholder=\"password\" style=\"width: 150px\"><input type=\"button\" value=\"Save\" onClick=\"{localStorage.setItem('key', key=document.all.myKey.value)}\">\n"
   "</div>\n"
   "</body>\n"
   "</html>\n";
